name: Build and Publish PDFs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Create tag if necessary
        id: version
        uses: fregante/daily-version-action@v2
        with:
          prefix: v

      - name: Compile English version
        run: |
          xelatex -synctex=1 -interaction=nonstopmode "\def\version{${{ steps.version.outputs.version }}} \input{cv_english.tex}"
          xelatex -synctex=1 -interaction=nonstopmode "\def\version{${{ steps.version.outputs.version }}} \input{cv_german.tex}"

      - name: Setup GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages

      - name: Copy PDFs
        run: |
          mkdir -p output
          mv cv_english.pdf output/
          mv cv_german.pdf output/

      - name: Deploy PDFs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          publish_branch: gh-pages
