name: Build and Publish PDFs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra

      - name: Compile English version
        run: |
          xelatex -interaction=nonstopmode -jobname=english "\def\language{english} \input{cv.tex}"

      - name: Compile German version
        run: |
          xelatex -interaction=nonstopmode -jobname=german "\def\language{german} \input{cv.tex}"

      - name: Setup GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages

      - name: Copy PDFs
        run: |
          mkdir -p output
          mv english.pdf output/
          mv german.pdf output/

      - name: Deploy PDFs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          publish_branch: gh-pages
